Include "assets/rust-toolchain" file to simplify hacspec workflow.
cryspen/bertie pull request #39
Opened 2022-08-25 12:02 UTC by duesee

2022-09-12 07:18 UTC, franziskuskiefer requested changes
What's the purpose of this PR?

The nightly version in hacspec changes and always tracking that here is error prone. Also, it is not necessary to use the hacspec nightly version to build hacspec crates. It's only used for the hacspec typechecker.

2022-09-14 17:42 UTC, duesee commented
I've updated the PR description.

2022-10-05 09:24 UTC, franziskuskiefer approved these changes
lgtm with the nit

2022-10-05 09:24 UTC, franziskuskiefer commented on README.md
> +Note: You do not need to do anything of this when you just want to build and run Bertie. This is only if you intend to *work* on Bertie, i.e., change its core and contribute the changes to the projec
```suggestion
Note: You do not need to do any of this when you just want to build and run Bertie. This is only if you intend to *work* on Bertie, i.e., change its core and contribute the changes to the project.
```

2022-10-05 10:55 UTC, merged